spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bezant_core?characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: 1234qwer
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      validation-timeout: 1000
      connection-timeout: 30000
      max-lifetime: 1800000
      initialization-fail-timeout: 0
      pool-name: bezant_core
      data-source-properties:
        useServerPrepStmts: false     # (MYSQL) recommended for performance
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        autoReconnect: true
        connectTimeout: 2000         # (MYSQL) connectTimeout
        socketTimeout: 5000          # (MYSQL) socketTimeout
        useTimezone: true
        serverTimezone: UTC
        useAffectedRows: true
        useSSL: false
        rewriteBatchedStatements: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

